apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-pvc.yml
  - grafana-deployment.yml
  - grafana-service.yml
  - grafana-configmap.yml
  - grafana-pv.yml
  - grafana-storage-class.yml