apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-storage-pvc
  labels:
    vol: psql-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: psql-storage