apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: local
spec:
  storageClassName: psql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jlto/Koce/Minikube/PVs/psql"