apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rest1
  name: rest1
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: rest1