apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: wms1
  name: wms1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wms1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: wms1
    spec:
      containers:
        - command:
            - /opt/docker/bin/wmscore
            - "7345"
          env:
            - name: NODE1_IP
              value: wms1
            - name: NODE1_PORT
              value: "7345"
            - name: NODE2_IP
              value: wms2
            - name: NODE2_PORT
              value: "7355"
            - name: NODE3_IP
              value: wms3
            - name: NODE3_PORT
              value: "7356"
            - name: NODE_IP
              value: wms1
            - name: NODE_PORT
              value: "7345"
          image: 192.168.1.50:5555/wms_new:0.2
          name: wms1
          ports:
            - containerPort: 17345
              protocol: TCP
      restartPolicy: Always
