apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: wms1
  name: wms1
spec:
  ports:
    - name: "17345"
      port: 17345
      targetPort: 17345
    - name: "7345"
      port: 7345
      targetPort: 7345  
  selector:
    io.kompose.service: wms1
