apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: wms1
  name: wms1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wms1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: wms1
    spec:
      containers:
        - name: wms1
        - command:
            - /opt/docker/bin/wmscore
            - "7345"
          env:
            - name: NODE1_IP
              value: wms1.default.svc
            - name: NODE1_PORT
              value: "7345"
            - name: NODE2_IP
              value: wms2.default.svc
            - name: NODE2_PORT
              value: "7355"
            - name: NODE3_IP
              value: wms3.default.svc
            - name: NODE3_PORT
              value: "7356"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
                  
            - name: NODE_PORT
              value: "7345"
          image: 192.168.1.50:5555/wms_new:0.2
          name: wms1
          ports:
            - containerPort: 17345
              protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: media-driver
      restartPolicy: Always
      volumes:
      - name: media-driver
        emptyDir:
          medium: Memory
          name: media-driver