apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: wms3
  name: wms3
spec:
  ports:
    - name: "17356"
      port: 17356
      targetPort: 17356
    - name: "7356"
      port: 7356
      targetPort: 7356
  selector:
    io.kompose.service: wms3
