apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-storage-pvc
  labels:
    vol: psql-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  hostPath:
    path: "/home/jlto/Koce/Minikube/PVs/psql"