apiVersion: v1
kind: Service
metadata:
  labels:
    env: webpage
  name: webpage
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443      
  selector:
    env: webpage
